// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: model/client.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientValidateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Data  map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ClientValidateData) Reset() {
	*x = ClientValidateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientValidateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientValidateData) ProtoMessage() {}

func (x *ClientValidateData) ProtoReflect() protoreflect.Message {
	mi := &file_model_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientValidateData.ProtoReflect.Descriptor instead.
func (*ClientValidateData) Descriptor() ([]byte, []int) {
	return file_model_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientValidateData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientValidateData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClientData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool              `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id      string            `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Address string            `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Tag     string            `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Data    map[string]string `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Types that are assignable to Ctx:
	//	*ClientData_BrokerCtx
	//	*ClientData_RelayCtx
	//	*ClientData_P2PCtx
	Ctx isClientData_Ctx `protobuf_oneof:"ctx"`
}

func (x *ClientData) Reset() {
	*x = ClientData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientData) ProtoMessage() {}

func (x *ClientData) ProtoReflect() protoreflect.Message {
	mi := &file_model_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientData.ProtoReflect.Descriptor instead.
func (*ClientData) Descriptor() ([]byte, []int) {
	return file_model_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientData) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ClientData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientData) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ClientData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (m *ClientData) GetCtx() isClientData_Ctx {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (x *ClientData) GetBrokerCtx() *BrokerClientContext {
	if x, ok := x.GetCtx().(*ClientData_BrokerCtx); ok {
		return x.BrokerCtx
	}
	return nil
}

func (x *ClientData) GetRelayCtx() *RelayClientContext {
	if x, ok := x.GetCtx().(*ClientData_RelayCtx); ok {
		return x.RelayCtx
	}
	return nil
}

func (x *ClientData) GetP2PCtx() *P2PClientContext {
	if x, ok := x.GetCtx().(*ClientData_P2PCtx); ok {
		return x.P2PCtx
	}
	return nil
}

type isClientData_Ctx interface {
	isClientData_Ctx()
}

type ClientData_BrokerCtx struct {
	BrokerCtx *BrokerClientContext `protobuf:"bytes,7,opt,name=brokerCtx,proto3,oneof"`
}

type ClientData_RelayCtx struct {
	RelayCtx *RelayClientContext `protobuf:"bytes,8,opt,name=relayCtx,proto3,oneof"`
}

type ClientData_P2PCtx struct {
	P2PCtx *P2PClientContext `protobuf:"bytes,9,opt,name=p2pCtx,proto3,oneof"`
}

func (*ClientData_BrokerCtx) isClientData_Ctx() {}

func (*ClientData_RelayCtx) isClientData_Ctx() {}

func (*ClientData_P2PCtx) isClientData_Ctx() {}

type ClientPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ClientPing) Reset() {
	*x = ClientPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPing) ProtoMessage() {}

func (x *ClientPing) ProtoReflect() protoreflect.Message {
	mi := &file_model_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPing.ProtoReflect.Descriptor instead.
func (*ClientPing) Descriptor() ([]byte, []int) {
	return file_model_client_proto_rawDescGZIP(), []int{2}
}

func (x *ClientPing) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type ClientSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *ClientSearch) Reset() {
	*x = ClientSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSearch) ProtoMessage() {}

func (x *ClientSearch) ProtoReflect() protoreflect.Message {
	mi := &file_model_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSearch.ProtoReflect.Descriptor instead.
func (*ClientSearch) Descriptor() ([]byte, []int) {
	return file_model_client_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSearch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientSearch) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type Clients struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Clients []string `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
}

func (x *Clients) Reset() {
	*x = Clients{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clients) ProtoMessage() {}

func (x *Clients) ProtoReflect() protoreflect.Message {
	mi := &file_model_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clients.ProtoReflect.Descriptor instead.
func (*Clients) Descriptor() ([]byte, []int) {
	return file_model_client_proto_rawDescGZIP(), []int{4}
}

func (x *Clients) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Clients) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Clients) GetClients() []string {
	if x != nil {
		return x.Clients
	}
	return nil
}

var File_model_client_proto protoreflect.FileDescriptor

var file_model_client_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x1a, 0x12, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x32, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x01, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x37, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x93, 0x03, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x3a, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x74, 0x78, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48,
	0x00, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x74, 0x78, 0x12, 0x37, 0x0a, 0x08,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x74, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x43, 0x74, 0x78, 0x12, 0x31, 0x0a, 0x06, 0x70, 0x32, 0x70, 0x43, 0x74, 0x78, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x32,
	0x50, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48, 0x00,
	0x52, 0x06, 0x70, 0x32, 0x70, 0x43, 0x74, 0x78, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x42, 0x05, 0x0a, 0x03, 0x63, 0x74, 0x78, 0x22, 0x20, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x0c, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x55, 0x0a, 0x07,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_client_proto_rawDescOnce sync.Once
	file_model_client_proto_rawDescData = file_model_client_proto_rawDesc
)

func file_model_client_proto_rawDescGZIP() []byte {
	file_model_client_proto_rawDescOnce.Do(func() {
		file_model_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_client_proto_rawDescData)
	})
	return file_model_client_proto_rawDescData
}

var file_model_client_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_model_client_proto_goTypes = []interface{}{
	(*ClientValidateData)(nil),  // 0: model.ClientValidateData
	(*ClientData)(nil),          // 1: model.ClientData
	(*ClientPing)(nil),          // 2: model.ClientPing
	(*ClientSearch)(nil),        // 3: model.ClientSearch
	(*Clients)(nil),             // 4: model.Clients
	nil,                         // 5: model.ClientValidateData.DataEntry
	nil,                         // 6: model.ClientData.DataEntry
	(*BrokerClientContext)(nil), // 7: model.BrokerClientContext
	(*RelayClientContext)(nil),  // 8: model.RelayClientContext
	(*P2PClientContext)(nil),    // 9: model.P2PClientContext
}
var file_model_client_proto_depIdxs = []int32{
	5, // 0: model.ClientValidateData.data:type_name -> model.ClientValidateData.DataEntry
	6, // 1: model.ClientData.data:type_name -> model.ClientData.DataEntry
	7, // 2: model.ClientData.brokerCtx:type_name -> model.BrokerClientContext
	8, // 3: model.ClientData.relayCtx:type_name -> model.RelayClientContext
	9, // 4: model.ClientData.p2pCtx:type_name -> model.P2PClientContext
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_model_client_proto_init() }
func file_model_client_proto_init() {
	if File_model_client_proto != nil {
		return
	}
	file_model_broker_proto_init()
	file_model_relay_proto_init()
	file_model_p2p_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_model_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientValidateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clients); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_model_client_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ClientData_BrokerCtx)(nil),
		(*ClientData_RelayCtx)(nil),
		(*ClientData_P2PCtx)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_client_proto_goTypes,
		DependencyIndexes: file_model_client_proto_depIdxs,
		MessageInfos:      file_model_client_proto_msgTypes,
	}.Build()
	File_model_client_proto = out.File
	file_model_client_proto_rawDesc = nil
	file_model_client_proto_goTypes = nil
	file_model_client_proto_depIdxs = nil
}
