// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: network/model/network.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderData_Type int32

const (
	HeaderData_NORMAL HeaderData_Type = 0
	HeaderData_ACK    HeaderData_Type = 1
	HeaderData_ACKR   HeaderData_Type = 2
)

// Enum value maps for HeaderData_Type.
var (
	HeaderData_Type_name = map[int32]string{
		0: "NORMAL",
		1: "ACK",
		2: "ACKR",
	}
	HeaderData_Type_value = map[string]int32{
		"NORMAL": 0,
		"ACK":    1,
		"ACKR":   2,
	}
)

func (x HeaderData_Type) Enum() *HeaderData_Type {
	p := new(HeaderData_Type)
	*p = x
	return p
}

func (x HeaderData_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeaderData_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_network_model_network_proto_enumTypes[0].Descriptor()
}

func (HeaderData_Type) Type() protoreflect.EnumType {
	return &file_network_model_network_proto_enumTypes[0]
}

func (x HeaderData_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeaderData_Type.Descriptor instead.
func (HeaderData_Type) EnumDescriptor() ([]byte, []int) {
	return file_network_model_network_proto_rawDescGZIP(), []int{0, 0}
}

type HeaderData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          HeaderData_Type `protobuf:"varint,1,opt,name=type,proto3,enum=model.HeaderData_Type" json:"type,omitempty"`
	Id            string          `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ContentType   string          `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`
	ContentLength uint32          `protobuf:"varint,4,opt,name=contentLength,proto3" json:"contentLength,omitempty"`
}

func (x *HeaderData) Reset() {
	*x = HeaderData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_model_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderData) ProtoMessage() {}

func (x *HeaderData) ProtoReflect() protoreflect.Message {
	mi := &file_network_model_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderData.ProtoReflect.Descriptor instead.
func (*HeaderData) Descriptor() ([]byte, []int) {
	return file_network_model_network_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderData) GetType() HeaderData_Type {
	if x != nil {
		return x.Type
	}
	return HeaderData_NORMAL
}

func (x *HeaderData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HeaderData) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *HeaderData) GetContentLength() uint32 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

var File_network_model_network_proto protoreflect.FileDescriptor

var file_network_model_network_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x22, 0xb7, 0x01, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x25, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x43, 0x4b, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x43, 0x4b, 0x52, 0x10, 0x02, 0x42, 0x10,
	0x5a, 0x0e, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_network_model_network_proto_rawDescOnce sync.Once
	file_network_model_network_proto_rawDescData = file_network_model_network_proto_rawDesc
)

func file_network_model_network_proto_rawDescGZIP() []byte {
	file_network_model_network_proto_rawDescOnce.Do(func() {
		file_network_model_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_network_model_network_proto_rawDescData)
	})
	return file_network_model_network_proto_rawDescData
}

var file_network_model_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_network_model_network_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_network_model_network_proto_goTypes = []interface{}{
	(HeaderData_Type)(0), // 0: model.HeaderData.Type
	(*HeaderData)(nil),   // 1: model.HeaderData
}
var file_network_model_network_proto_depIdxs = []int32{
	0, // 0: model.HeaderData.type:type_name -> model.HeaderData.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_network_model_network_proto_init() }
func file_network_model_network_proto_init() {
	if File_network_model_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_network_model_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_network_model_network_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_model_network_proto_goTypes,
		DependencyIndexes: file_network_model_network_proto_depIdxs,
		EnumInfos:         file_network_model_network_proto_enumTypes,
		MessageInfos:      file_network_model_network_proto_msgTypes,
	}.Build()
	File_network_model_network_proto = out.File
	file_network_model_network_proto_rawDesc = nil
	file_network_model_network_proto_goTypes = nil
	file_network_model_network_proto_depIdxs = nil
}
